-- Create the ApplicationDraft table for multi-step application submission
CREATE TABLE `ApplicationDraft` (
    `id` VARCHAR(191) NOT NULL,
    `currentStep` INTEGER NOT NULL DEFAULT 0,
    `ocrSessionId` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NULL,
    `firstName` VARCHAR(191) NULL,
    `middleInitial` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `studentId` VARCHAR(191) NULL,
    `idImagePath` VARCHAR(191) NULL,
    `dateOfBirth` DATETIME(3) NULL,
    `placeOfBirth` VARCHAR(191) NULL,
    `gender` ENUM('MALE', 'FEMALE', 'LGBTQIA', 'PREFER_NOT_TO_SAY') NULL,
    `cellphoneNumber` VARCHAR(191) NULL,
    `houseAddress` VARCHAR(191) NULL,
    `facebookLink` VARCHAR(191) NULL,
    `college` VARCHAR(191) NULL,
    `program` VARCHAR(191) NULL,
    `section` VARCHAR(191) NULL,
    `campus` ENUM('SAN_BARTOLOME_MAIN', 'SAN_FRANCISCO', 'BATASAN') NULL,
    `office` ENUM('SECRETARIAT_OFFICE', 'RELATIONS_OFFICE', 'FINANCE_OFFICE', 'LOGISTICS_OFFICE', 'CREATIVES_OFFICE', 'MANAGEMENT_AND_DEVELOPMENT_OFFICE', 'STARTUP_DEVELOPERS_OFFICE') NULL,
    `certificateOfRegistration` VARCHAR(191) NULL,
    `curriculumVitae` VARCHAR(191) NULL,
    `interestsSkillsHobbies` TEXT NULL,
    `organizationHistory` TEXT NULL,
    `portfolio` VARCHAR(191) NULL,
    `githubOrProjectLinks` VARCHAR(191) NULL,
    `previousWorksAchievements` TEXT NULL,
    `manual_application` BOOLEAN NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ApplicationDraft_ocrSessionId_key`(`ocrSessionId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
