-- AlterTable
ALTER TABLE `applicant` ADD COLUMN `adminMessage` VARCHAR(191) NULL,
    MODIFY `status` ENUM('APPROVED', 'PENDING_REVIEW', 'REJECTED', 'CANCELLED', 'RESUBMIT') NOT NULL DEFAULT 'PENDING_REVIEW';
